const ENTIDADES = [
  'AREA', 'CATALOGODESCRIPCIONGASTO', 'CLIENTE', 'GASTODIARIO', 'GASTOFIJO',
  'INGENIERO', 'MUNICIPIO', 'NOMINA', 'ORDEN', 'PUESTO', 'RECIBO', 'ROL',
  'SERVICIO', 'SUBTIPOTERRENO', 'TIPOSERVICIO', 'TIPOTERRENO', 'TRABAJADOR',
  'USUARIO', 'ZONAEJIDAL'
];

const ACCIONES = ['CREATE', 'READ', 'UPDATE', 'DELETE'];

// Generación dinámica del objeto PERMISOS en formato ENTIDAD_ACCION
export const PERMISOS = ENTIDADES.reduce((acc, entidad) => {
  ACCIONES.forEach((accion) => {
    const key = `${entidad}_${accion}`;
    acc[key] = key;
  });
  return acc;
}, {});

/*
export const PERMISOS = {
  // AREA
  AREA_CREATE: 'AREA_CREATE',
  AREA_READ: 'AREA_READ',
  AREA_UPDATE: 'AREA_UPDATE',
  AREA_DELETE: 'AREA_DELETE',

  // CATALOGODESCRIPCIONGASTO
  CATALOGODESCRIPCIONGASTO_CREATE: 'CATALOGODESCRIPCIONGASTO_CREATE',
  CATALOGODESCRIPCIONGASTO_READ: 'CATALOGODESCRIPCIONGASTO_READ',
  CATALOGODESCRIPCIONGASTO_UPDATE: 'CATALOGODESCRIPCIONGASTO_UPDATE',
  CATALOGODESCRIPCIONGASTO_DELETE: 'CATALOGODESCRIPCIONGASTO_DELETE',

  // CLIENTE
  CLIENTE_CREATE: 'CLIENTE_CREATE',
  CLIENTE_READ: 'CLIENTE_READ',
  CLIENTE_UPDATE: 'CLIENTE_UPDATE',
  CLIENTE_DELETE: 'CLIENTE_DELETE',

  // GASTODIARIO
  GASTODIARIO_CREATE: 'GASTODIARIO_CREATE',
  GASTODIARIO_READ: 'GASTODIARIO_READ',
  GASTODIARIO_UPDATE: 'GASTODIARIO_UPDATE',
  GASTODIARIO_DELETE: 'GASTODIARIO_DELETE',

  // GASTOFIJO
  GASTOFIJO_CREATE: 'GASTOFIJO_CREATE',
  GASTOFIJO_READ: 'GASTOFIJO_READ',
  GASTOFIJO_UPDATE: 'GASTOFIJO_UPDATE',
  GASTOFIJO_DELETE: 'GASTOFIJO_DELETE',

  // INGENIERO
  INGENIERO_CREATE: 'INGENIERO_CREATE',
  INGENIERO_READ: 'INGENIERO_READ',
  INGENIERO_UPDATE: 'INGENIERO_UPDATE',
  INGENIERO_DELETE: 'INGENIERO_DELETE',

  // MUNICIPIO
  MUNICIPIO_CREATE: 'MUNICIPIO_CREATE',
  MUNICIPIO_READ: 'MUNICIPIO_READ',
  MUNICIPIO_UPDATE: 'MUNICIPIO_UPDATE',
  MUNICIPIO_DELETE: 'MUNICIPIO_DELETE',

  // NOMINA
  NOMINA_CREATE: 'NOMINA_CREATE',
  NOMINA_READ: 'NOMINA_READ',
  NOMINA_UPDATE: 'NOMINA_UPDATE',
  NOMINA_DELETE: 'NOMINA_DELETE',

  // ORDEN
  ORDEN_CREATE: 'ORDEN_CREATE',
  ORDEN_READ: 'ORDEN_READ',
  ORDEN_UPDATE: 'ORDEN_UPDATE',
  ORDEN_DELETE: 'ORDEN_DELETE',

  // PUESTO
  PUESTO_CREATE: 'PUESTO_CREATE',
  PUESTO_READ: 'PUESTO_READ',
  PUESTO_UPDATE: 'PUESTO_UPDATE',
  PUESTO_DELETE: 'PUESTO_DELETE',

  // RECIBO
  RECIBO_CREATE: 'RECIBO_CREATE',
  RECIBO_READ: 'RECIBO_READ',
  RECIBO_UPDATE: 'RECIBO_UPDATE',
  RECIBO_DELETE: 'RECIBO_DELETE',

  // ROL
  ROL_CREATE: 'ROL_CREATE',
  ROL_READ: 'ROL_READ',
  ROL_UPDATE: 'ROL_UPDATE',
  ROL_DELETE: 'ROL_DELETE',

  // SERVICIO
  SERVICIO_CREATE: 'SERVICIO_CREATE',
  SERVICIO_READ: 'SERVICIO_READ',
  SERVICIO_UPDATE: 'SERVICIO_UPDATE',
  SERVICIO_DELETE: 'SERVICIO_DELETE',

  // SUBTIPOTERRENO
  SUBTIPOTERRENO_CREATE: 'SUBTIPOTERRENO_CREATE',
  SUBTIPOTERRENO_READ: 'SUBTIPOTERRENO_READ',
  SUBTIPOTERRENO_UPDATE: 'SUBTIPOTERRENO_UPDATE',
  SUBTIPOTERRENO_DELETE: 'SUBTIPOTERRENO_DELETE',

  // TIPOSERVICIO
  TIPOSERVICIO_CREATE: 'TIPOSERVICIO_CREATE',
  TIPOSERVICIO_READ: 'TIPOSERVICIO_READ',
  TIPOSERVICIO_UPDATE: 'TIPOSERVICIO_UPDATE',
  TIPOSERVICIO_DELETE: 'TIPOSERVICIO_DELETE',

  // TIPOTERRENO
  TIPOTERRENO_CREATE: 'TIPOTERRENO_CREATE',
  TIPOTERRENO_READ: 'TIPOTERRENO_READ',
  TIPOTERRENO_UPDATE: 'TIPOTERRENO_UPDATE',
  TIPOTERRENO_DELETE: 'TIPOTERRENO_DELETE',

  // TRABAJADOR
  TRABAJADOR_CREATE: 'TRABAJADOR_CREATE',
  TRABAJADOR_READ: 'TRABAJADOR_READ',
  TRABAJADOR_UPDATE: 'TRABAJADOR_UPDATE',
  TRABAJADOR_DELETE: 'TRABAJADOR_DELETE',

  // USUARIO
  USUARIO_CREATE: 'USUARIO_CREATE',
  USUARIO_READ: 'USUARIO_READ',
  USUARIO_UPDATE: 'USUARIO_UPDATE',
  USUARIO_DELETE: 'USUARIO_DELETE',

  // ZONAEJIDAL
  ZONAEJIDAL_CREATE: 'ZONAEJIDAL_CREATE',
  ZONAEJIDAL_READ: 'ZONAEJIDAL_READ',
  ZONAEJIDAL_UPDATE: 'ZONAEJIDAL_UPDATE',
  ZONAEJIDAL_DELETE: 'ZONAEJIDAL_DELETE',
}

*/